# Generated by Django 3.2.7 on 2021-10-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(blank=True, max_length=200, null=True)),
                ('StudentId', models.CharField(blank=True, max_length=50, null=True)),
                ('LectureAttend', models.IntegerField(blank=True, null=True)),
                ('TotalLectures', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(blank=True, max_length=200, null=True)),
                ('StudentId', models.CharField(blank=True, max_length=50, null=True)),
                ('PhysicsMarks', models.IntegerField(blank=True, null=True)),
                ('ChemistryMarks', models.IntegerField(blank=True, null=True)),
                ('EnglishMarks', models.IntegerField(blank=True, null=True)),
                ('MathsMarks', models.IntegerField(blank=True, null=True)),
                ('ComputerMarks', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
